In [48]:
import numpy as np

a = np.arange(10, 30).reshape(4, 5)
# explanation: comma separates the arrays and colon does the positional selection
# 2dArray[rows, columns]
# double colon: get every n^th value e.g. ::2 menas print every second value and 2::3 means get every third value starting from third pos.
red    = a[0, 1:4]  # get one-dim. subarray of row 0, start:1 (pos=2) end:4 (not included, pos=4)
blue   = a[0:3,:2:4]  # get one-dim. subarrays (index 1,2,3) of column 0
green  = a[0:3,2] # get a two-dim. subarray of every second element by row and column
teal = a[::1,1::2]    # get the second column
yellow = a[0:1,0]

print('red:',red,'\nblue:',blue,'\ngreen:',green,'\nteal:',teal, '\nyellow:', yellow)


red: [11 12 13] 
blue: [[10]
 [15]
 [20]] 
green: [12 17 22] 
teal: [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
yellow: [10]


Class exercise: cube
Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
Slice out [3 12 21].
Slice out all y-values where x is 2 and z is 0.

In [96]:
a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)
#print('whole cube: \n',a, '\n---------------')
first = a[1,1]
second = a[:,1,0]
third = a[0, :, 2]
print(first)
print(second)
print(third)



[12 13 14]
[ 3 12 21]
[2 5 8]


<h2>Exercise numpy and csv</h2>
load the csv file: befkbhalderstatkode.csv into a numpy ndarray<br>
How many german children were 0 years old in 2015?<br>
create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data<br>
create a new function like previous so that it can sum values for all ages if age is not provided to the function<br>
further add functionality to sum values if citizenship or area was not provided to function.<br>
create a new function that can also give average values for each year if year whas not provided.<br>
create a function, that given year and nationality can return which area had the most of these nationals by that year. Test it by finding out which area had the most Moroccan people in both 1992 and 2015<br>
Find the Area(s) where fewest foreingers lived in Copenhagen in 1992 and 2015 respectively<br>
Find out what age most French people have in 2015<br>

In [115]:
filename = '../data/befkbhalderstatkode.csv'
bef_stats_df = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
print(type(bef_stats_df),' of size: ',bef_stats_df.size)

dd = bef_stats_df

german_mask = (dd[:,0] == 2015) & (dd[:,3] == 5180) & (dd[:,2] == 0)
print(dd[german_mask])

np.sum(dd[german_mask][:,4])

<class 'numpy.ndarray'>  of size:  2712585
[[2015    1    0 5180    3]
 [2015    2    0 5180    5]
 [2015    3    0 5180    7]
 [2015    4    0 5180    1]
 [2015    5    0 5180    1]
 [2015    6    0 5180    2]
 [2015    8    0 5180    2]
 [2015    9    0 5180    6]
 [2015   10    0 5180    8]]


35